apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mlops-eyes
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: mlops-backend
        static_configs:
          - targets: ["backend-service:8000"]
