apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: mlopseyes-backend
    newName: ghcr.io/crips64/mlopseyes-backend
    newTag: sha-9aae683bbfac43ef217f74a12b9ab309a574471e
  - name: mlopseyes-frontend
    newName: ghcr.io/crips64/mlopseyes-frontend
    newTag: sha-9aae683bbfac43ef217f74a12b9ab309a574471e
