apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: mlopseyes-backend
    newName: ghcr.io/your-github-owner/mlopseyes-backend
    newTag: latest
  - name: mlopseyes-frontend
    newName: ghcr.io/your-github-owner/mlopseyes-frontend
    newTag: latest
